# Generated by Django 5.0.9 on 2024-09-13 02:32
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_rename_receipe_commentres_recipe"),
    ]

    operations = [
        TrigramExtension()
    ]
